### PR TITLE
EOBS-302: Fixing location missing when defining start date

### PR DESCRIPTION
**Pull request by Gimpneek**
- Changing way report looks at Location for the report. Uses current_location_id from nh.clinical.patient instead of last record in transfer history as this would be filtered by start_date when printing report

### CODE REVIEW

**Comment by moderatemisbehaviour** [comment]
Got a failing test [here](https://travis-ci.org/NeovaHealth/openeobs/jobs/154505759).

**Comment by Gimpneek** [comment]
Test was failing due to stupid way that `nh.clinical.api.demo` creates wards. Basically created another location with the same code as an existing one

**Comment by moderatemisbehaviour** [comment]
:shipit:

**Comment by Nayira** [comment]
Tests passed on feature branch - :shipit:

**Pull request merged**
