### PR TITLE
Eobs 329 & 330

### PR DESCRIPTION
**Pull request by moderatemisbehaviour**
- Cancelling EWS when obs_stop set to True
- Restarting EWS when obs_stop set to False
- Showing Observations Stopped and Reason on mobile and desktop

### CODE REVIEW

**Comment by Gimpneek** [comment]
:shipit:

**Comment by moderatemisbehaviour** [comment]
:shipit:

**Comment by moderatemisbehaviour** [comment]
Just a couple of docstrings to add as discussed but other than that :shipit: @ ef5e09d

**Comment by Nayira** [comment]
Tests for 329, 446 and 449 Pass. :shipit:

**Pull request merged**
