### PR TITLE
Eobs 596 refused observation graph

### PR DESCRIPTION
**Pull request by Gimpneek**
- Adding abillity to render refused observations to nh_graphs
- Adding CSS to make it look amazing
- Adding override to `EWSChartWidget` in Odoo frontend to display refused chart on for Mental Health
- Adding override to observation report to use an amended version of the observation chart definition for mental health observations
- Adding override to `nh_lib.js` on Mobile so `NHMobilePatient` only displays refused chart on Mental Health

### CODE REVIEW

**Comment by moderatemisbehaviour** [comment]
LGTM :shipit:

**Comment by moderatemisbehaviour** [comment]
Glorious :shipit:

**Comment by moderatemisbehaviour** [comment]
:shipit:

**Comment by stuandgray** [comment]
:shipit:

**Pull request merged**
